os2 run ply_to_rviz graph_nav_visualizer
Traceback (most recent call last):
  File "/home/virani/learn_ros_ws/install/ply_to_rviz/lib/ply_to_rviz/graph_nav_visualizer", line 33, in <module>
    sys.exit(load_entry_point('ply-to-rviz', 'console_scripts', 'graph_nav_visualizer')())
  File "/home/virani/learn_ros_ws/build/ply_to_rviz/ply_to_rviz/graph_nav_visualizer.py", line 105, in main
    node = GraphNavVisualizer(map_path)
  File "/home/virani/learn_ros_ws/build/ply_to_rviz/ply_to_rviz/graph_nav_visualizer.py", line 16, in __init__
    self.current_graph, self.current_waypoints, self.current_waypoint_snapshots, _, _, _ = self.load_map(map_path)
  File "/home/virani/learn_ros_ws/build/ply_to_rviz/ply_to_rviz/graph_nav_visualizer.py", line 30, in load_map
    current_graph.ParseFromString(data)
TypeError: descriptor 'ParseFromString' for 'google._upb._message.Message' objects doesn't apply to a 'bytes' object
[ros2run]: Process exited with failure 1
(venv) venvvirani@virani-HP-Laptop-15s-du1x
